# Generated by Django 5.0.6 on 2024-06-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_alter_comment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
