# Generated by Django 5.0.6 on 2024-06-07 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_alter_person_gender_alter_person_marital_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.person')),
            ],
            options={
                'unique_together': {('movie', 'person')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(through='movie_app.DirectorMovie', to='movie_app.person'),
        ),
    ]
