# Generated by Django 5.0.6 on 2024-06-12 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_alter_person_gender_alter_person_marital_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorMovie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='movie_app.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies_directed', to='movie_app.person')),
            ],
            options={
                'unique_together': {('movie_id', 'person_id')},
            },
        ),
    ]
