# Generated by Django 5.0.6 on 2024-06-16 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_moviegenre'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenreAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.moviegenre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.movie')),
            ],
            options={
                'unique_together': {('movie', 'genre')},
            },
        ),
    ]
