# Generated by Django 5.0.6 on 2024-06-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0011_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='UserPassword',
            field=models.CharField(max_length=150),
        ),
    ]
